spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: products
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
        - id: carts
          uri: lb://cart-service
          predicates:
            - Path=/api/carts/**
#        - id: delivery
#            uri: lb://delivery-service
#            predicates:
#              - Path=/api/delivery/**
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
#        - id: visits-service
#          uri: lb://visits-service
#          predicates:
#            - Path=/api/visit/**
#          filters:
#            - StripPrefix=2
#        - id: customers-service
#          uri: lb://customers-service
#          predicates:
#            - Path=/api/customer/**
#          filters:
#            - StripPrefix=2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

server:
  port: 8080   # HTTP (Tomcat) port
